version: '3.8'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "test"
      MONGO_INITDB_ROOT_PASSWORD: "test"
      MONGO_INITDB_DATABASE: "test"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
